# Generated by Django 4.0 on 2022-01-05 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('black', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blaklist', models.ForeignKey(db_column='black_list', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist', to='black.blacklist')),
            ],
        ),
    ]
