# Generated by Django 4.0 on 2022-01-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectSexModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('select_sex', models.CharField(max_length=30)),
            ],
        ),
    ]
