# Generated by Django 4.0.1 on 2022-01-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_communitymodel_imput'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymodel',
            name='admin_name',
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
    ]
