# Generated by Django 4.0.1 on 2022-01-12 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usermodel_email_alter_usermodel_login_id_and_more'),
        ('community', '0005_alter_postmodel_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post_author_id',
            field=models.ForeignKey(db_column='text_author_id', on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to='user.usermodel'),
            preserve_default=False,
        ),
    ]
