# Generated by Django 4.0 on 2022-01-05 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymodel',
            name='comm_admin_id',
            field=models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='user.usermodel'),
        ),
    ]
