# Generated by Django 4.0.1 on 2022-01-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='connection',
            field=models.BooleanField(default=True),
        ),
    ]
