# Generated by Django 4.0.1 on 2022-01-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_communitymodel_community_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
