# Generated by Django 4.0 on 2021-12-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.CharField(max_length=16)),
                ('login_pw', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=10)),
                ('nickname', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['login_id', 'login_pw', 'email', 'name', 'sex', 'nickname'],
            },
        ),
    ]
