# Generated by Django 4.0 on 2022-01-03 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['id', 'login_id', 'login_pw', 'email', 'name', 'sex', 'nickname']},
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='User',
        ),
    ]
