# Generated by Django 4.0 on 2022-01-07 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_usermodel_connection_usermodel_sex_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('community_admin_id', models.PositiveIntegerField()),
                ('imput', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('post_contents', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.PositiveIntegerField()),
                ('post_author_id', models.ForeignKey(db_column='text_author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_author', to='user.usermodel')),
                ('post_community_id', models.ForeignKey(db_column='post_community_id', on_delete=django.db.models.deletion.CASCADE, related_name='post_community', to='community.communitymodel')),
            ],
        ),
        migrations.CreateModel(
            name='HeadModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('head', models.CharField(max_length=30)),
                ('head_community_id', models.ForeignKey(db_column='head_community_id', on_delete=django.db.models.deletion.CASCADE, related_name='head_community', to='community.communitymodel')),
                ('head_post_id', models.ForeignKey(db_column='head_post_id', on_delete=django.db.models.deletion.CASCADE, related_name='head_post', to='community.postmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_contents', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_author_id', models.ForeignKey(db_column='comment_author_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='user.usermodel')),
                ('comment_post_id', models.ForeignKey(db_column='comment_post_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='community.postmodel')),
            ],
        ),
    ]
