# Generated by Django 4.0 on 2022-01-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_id', models.CharField(max_length=30)),
                ('input_pw', models.CharField(max_length=100)),
            ],
        ),
    ]
