# Generated by Django 4.0 on 2022-01-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='connection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='sex_selection',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=30),
        ),
    ]
