# Generated by Django 4.0 on 2022-01-03 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_usermodel_options_alter_usermodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('view_count', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('author_id', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='author', to='user.usermodel')),
            ],
            options={
                'db_table': 'Text',
                'ordering': ['title', 'text', 'view_count', 'date', 'author_id'],
            },
        ),
    ]
