# Generated by Django 4.0 on 2022-01-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('selection', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'MainPage',
                'ordering': ['id', 'selection'],
            },
        ),
    ]
