# Generated by Django 4.0 on 2022-01-05 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('headtext', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('text_contents', models.TextField()),
                ('view_count', models.PositiveIntegerField()),
                ('text_date', models.DateTimeField(auto_now_add=True)),
                ('comm_id', models.ForeignKey(db_column='comm_id', on_delete=django.db.models.deletion.CASCADE, related_name='community', to='community.communitymodel')),
                ('head_id', models.ForeignKey(db_column='head_id', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='text_head', to='headtext.headtextmodel')),
            ],
        ),
    ]
