# Generated by Django 4.0.1 on 2022-01-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='connection',
            field=models.BooleanField(default='False'),
        ),
    ]
