# Generated by Django 4.0 on 2022-01-05 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('text', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='comment_author_id',
            field=models.ForeignKey(db_column='comment_author_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='user.usermodel'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='text_field_id',
            field=models.ForeignKey(db_column='text_field_id', on_delete=django.db.models.deletion.CASCADE, related_name='text', to='text.textmodel'),
        ),
    ]
