# Generated by Django 4.0 on 2022-01-10 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='comm_id',
            field=models.ForeignKey(db_column='comm_id', on_delete=django.db.models.deletion.CASCADE, related_name='block', to='community.communitymodel'),
        ),
    ]
